#openapi: 3.0.0
#info:
#  title: Yanki Service API
#  version: 1.0.0
#  description: API for managing wallet customers
#
#servers:
#  - url: http://localhost/api/v1
#
#paths:
#  /wallets:
#    post:
#      operationId: createWallet
#      summary: Create new wallet
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/CreateWalletRequest'
#      responses:
#        '201':
#          description: Wallet created
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/CreateWalletResponse'
#        '400':
#          description: Bad request
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ResponseBase'
#
#components:
#  schemas:
#    ResponseBase:
#      type: object
#      properties:
#        message:
#          type: string
#
#    CreateWalletRequest:
#      type: object
#      properties:
#        documentNumber:
#          type: string
#        phoneNumber:
#          type: string
#        phoneImei:
#          type: string
#        email:
#          type: string
#      required:
#        - documentNumber
#        - phoneNumber
#        - phoneImei
#        - email
#
#    CreateWalletResponse:
#      type: object
#      properties:
#        documentNumber:
#          type: string
#        phoneNumber:
#          type: string
#        phoneImei:
#          type: string
#        email:
#          type: string
